apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/fourside/majel-app
    newTag: "190b9348c8f1409f4cc96d81bccf4b28b34b0c70"
  - name: ghcr.io/fourside/majel-sensors
    newTag: "190b9348c8f1409f4cc96d81bccf4b28b34b0c70"
