apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../../majel-news-record

images:
  - name: ghcr.io/fourside/majel-app
    newTag: "9c3b5369af3588db08e3919c9a0dc977c0295a78"
  - name: ghcr.io/fourside/majel-sensors
    newTag: "9c3b5369af3588db08e3919c9a0dc977c0295a78"
  - name: ghcr.io/fourside/majel-recorder
    newTag: "9c3b5369af3588db08e3919c9a0dc977c0295a78"
