apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/fourside/majel-app
    newTag: "37d111397e8c2e966ca2570e7e432e6c39d207bd"
  - name: ghcr.io/fourside/majel-sensors
    newTag: "37d111397e8c2e966ca2570e7e432e6c39d207bd"
