apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/fourside/majel.git
    targetRevision: main
    path: k8s/argocd/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: argocd-notifications-secret
      jsonPointers:
        - /data
  syncPolicy:
    automated:
      selfHeal: true
      # prune: false to prevent ArgoCD from accidentally deleting its own resources
      prune: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
