apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: majel
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.slack_webhook: ""
    notifications.argoproj.io/subscribe.on-sync-failed.slack_webhook: ""
    notifications.argoproj.io/subscribe.on-health-degraded.slack_webhook: ""
spec:
  project: default
  source:
    repoURL: https://github.com/fourside/majel.git
    targetRevision: main
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: majel
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
