apiVersion: ENC[AES256_GCM,data:blE=,iv:mMZdRRXT6oZ7gYLJAQ6UubOZXHuE2NfSNm0rfOLy3gQ=,tag:T4ESg8Ci1SfUIJX9P52bmw==,type:str]
kind: ENC[AES256_GCM,data:TF0hq+Ou,iv:sm0NhHevLGv/pg1IsCCZLIhhgNd6kM79J8oty78Aptg=,tag:IzS1TrvPPDX4JldNJ+Xuhg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:0a8jviiVp4bN7qUgomV5n6XuMYLEEuOcnT1y,iv:Hckb3tWMGGOBPSMUe3evku4xZLbt61zaEQd8cn5kW74=,tag:+ht3clsQAy38cholsdwPTA==,type:str]
    namespace: ENC[AES256_GCM,data:Frv/jLBQ,iv:npYeiUTYwjBhmphIIJ0UzoUs/kpHYMYVcCLptycUjXs=,tag:uHzETyKxS1+0VvFiKIjCZg==,type:str]
type: ENC[AES256_GCM,data:rqbr/L2n,iv:5ezIXorGHj4+SBwgRMrmY7sf7vjqFq7JEyQgR65saTI=,tag:vQzs4ez6CUqPvFTarIbgSQ==,type:str]
stringData:
    slack-webhook-url: ENC[AES256_GCM,data:nMWPOdHsk/6Ef0//NxLL9p0xXj3wvt4+FiuR6wfjVo6IRDLrjP0rufxW1sORgvMcOxlpmqqOUgv8rPh1Z4pdU5c+UxwVWZPOJgRpEjdlZA==,iv:xZBLBxFMSbBMK6vzFyD93EVS9j2ggYS9q01PfV2RHWg=,tag:n3M5TW+1plrfsgPGWg91Gg==,type:str]
sops:
    age:
        - recipient: age1qsj5x5cm98dl8r74xp80guvay8kjp0gz5gypqfdjzd9w59kuk5pquhjgef
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiaTlkNnkxUnhIRncwNGRp
            bE9yWVBoenRiR1dERFNSVC9pS1gwT0VMeVhRCll0ampwVmJnK0xWRHkwOHVwSjBx
            TVpjcFQ2SGcxQzlVZFkzdklzZm9qK1UKLS0tIEJLTUxVa2ExZXd2SXN4blFCLzNt
            bUttWjcyN1FMY1RpUnYyK2xlVEZPWnMKr7Ac1Xt8vL6a05w6TFtXy4/CBLLBgb3p
            DXQVBkD4DOnYqGc2bH6T8zYIk3goOxnSDZ9bgaPSDLhUnD88tETf3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T08:21:49Z"
    mac: ENC[AES256_GCM,data:GoFPm7hi6LsCzlputpX+Hk+M/2nZOhJqYubPipWDM/ZCpSk81PugiK64W8cqxruycd4BOJbUfYyhWQuzgwh0RS/LCXTQEsm7ewQolkmdvMBzcccbKMmjNjSw1LmBb8AChjRR7Nv/wnxWkqLTkTxEnae/u+i9vtNkd4HLUaTfnE4=,iv:4KEZMjitCohlwLZJEZn9+LSVwIJUk2OcJhrd+uCvmCA=,tag:2S0ATRrPgnbHVPv22v8bSA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
