apiVersion: v1
kind: Secret
metadata:
    name: argocd-notifications-secret
    annotations:
        kustomize.config.k8s.io/behavior: merge
stringData:
    slack-webhook-url: ENC[AES256_GCM,data:tVsXcY28bUtBc4l5DbwI6R6UppNb3RFODGyPKuaEtvq+A6nng49B1fL6QNDevsawa8T61ltxeA+Dp4O9yhaPzj9ee1vDIPVpOdz1urImBA==,iv:PTj2DPWbOBFsXGO9iwsqIuzhyAlQZZOhMif3iJKfewU=,tag:BWjlSY8qp7xw+HOi+5SoAA==,type:str]
sops:
    age:
        - recipient: age1qsj5x5cm98dl8r74xp80guvay8kjp0gz5gypqfdjzd9w59kuk5pquhjgef
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtRG9CbE45amluS09xV2pj
            Q0lyL2NCcnhYYW9ZTWNRSlo1VEVseUIwanljCmIxZmVWbVNKMVZmbUc3d1d0OFFa
            TzlJc2Vha0FQSTZESDlTdmdYWjFudFkKLS0tIHlUUTlCU2ROTXpDUzNGYWlPTGJl
            RkU2UVhHdytVeGVkQjVYMmIrak5EKzgKsAK8uOMeX6KMFn5pG0CfWYTla0dqoPjU
            J0t6H2Lnp52jGPIUv92/QFxVSp4z6q0GW/ROCjCzJTdetM4/dU3nTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T15:11:14Z"
    mac: ENC[AES256_GCM,data:2GM56d4LsvXUKhVt2GvuSQldPjLC6SJI80dOgRPFZuQN4yTnDsG4HNJllW8acFPr+q92i7mn2EiyTtdjBs7FRQ76j8GFS2e0OMVpWQRcGdwOEg8KbOwCIHY9cyOKcQ7a1CRWDPoWhHnai0Nk89A5qNXVIHqazNGpPgQK/ck7jt0=,iv:3m3uJ1Qb8XK3R4BWdEalv6CNjX/ENVblBfzzFYkvJyc=,tag:720MSOxlqU2/M++kftD+YQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
