apiVersion: v1
kind: Secret
metadata:
    name: argocd-notifications-secret
    namespace: argocd
    labels:
        app.kubernetes.io/component: notifications-controller
        app.kubernetes.io/name: argocd-notifications-controller
        app.kubernetes.io/part-of: argocd
    annotations:
        kustomize.config.k8s.io/behavior: merge
type: Opaque
stringData:
    slack-webhook-url: ENC[AES256_GCM,data:n71mHdYhDH37bZNm3ZRw+02zTj8g7OMbVO+UPvPM+qfUrqKCLXak0hvd/duXMMDDN6BtVPfd9wbhqSSEP63dMBHxTng98/bh/i+dL3bAjA==,iv:oWOkNiH5sE4iECXl7LeHwi7Qof7hC9JTl5JdXVlpItk=,tag:z1STylebns9xsLptvFrQWA==,type:str]
sops:
    age:
        - recipient: age1qsj5x5cm98dl8r74xp80guvay8kjp0gz5gypqfdjzd9w59kuk5pquhjgef
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnTDVGMXZtcW9BRk5NMHd0
            RHE3Y3FsNjljMm80ZFFSOWVBR21odzZCUDE0CkJwNUZ3djNjZ0lhKzVlV0VZWTJi
            bWg5bklGakVwNjA1YkxQTThwanUvMWMKLS0tIFVqdGRUdXN1aWw3UjhHQmJSa01F
            ZkJtVXQvd0ZtRWNvY013M3UwcllQTDgKrdtOxp9ZwIl1wVKZy8PeYcvvrT8MWlde
            ZFn2mrJuWmdJ8cDoPY2OcwfYIE2U58JCYcFh8e+6Ml3gPgg6/okvwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T14:17:18Z"
    mac: ENC[AES256_GCM,data:LfMpjWXT9gDm8S4yvk31FHrxoEvNmewcJVQrqkv75zcGvENBIM+O1UDzLxSOEzT7HrX2hSmrjjeRNl8zhx0qC7iBqQ2TeZq3uXJmq4VmEKtj+REGANGIjxQ2DcRypAcmPsSN6Ex7G+F+4PSEuIde3V1w1MXp7qx8f83zVselob4=,iv:j200/FQp7sxSk/rntGRIgnGMZ4fU6xgmgzDF7aqTJQQ=,tag:QtcnTMrFYyigSXclZ2MmoA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
