apiVersion: v1
kind: ConfigMap
metadata:
  name: majel-alsa-conf
  namespace: majel
data:
  asound.conf: |
    pcm.!default {
      type hw
      card 2
      device 0
    }
    ctl.!default {
      type hw
      card 2
    }
