apiVersion: v1
kind: ConfigMap
metadata:
  name: majel-config
  namespace: majel
data:
  PORT: "3000"
  TZ: "Asia/Tokyo"
  TTS_ENGINE: "voicevox"
  VOICEVOX_URL: "http://voicevox:50021"
  VOICEVOX_SPEAKER: "1"
