apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: majel

resources:
  - namespace.yaml
  - app-deployment.yaml
  - app-service.yaml
  - configmap.yaml
  - otel-serviceaccount.yaml
  - otel-clusterrole.yaml
  - otel-clusterrolebinding.yaml
  - otel-configmap.yaml
  - otel-daemonset.yaml

generators:
  - secret-generator.yaml
