apiVersion: ENC[AES256_GCM,data:sgo=,iv:XUj5oePyPjF/LwCE9XDrs0EzB6Y0mue+Zdt3g9zvs+E=,tag:5iTGwCbwHT8wKLwj2GzmPA==,type:str]
kind: ENC[AES256_GCM,data:TOuwptOM,iv:hLfV6kyjqiWvQ2vHIB2CSWQbDHtEy1X1ST6DoRMh/I0=,tag:3S0/Btt6ha2iYiJOQK5nag==,type:str]
metadata:
    name: ENC[AES256_GCM,data:VxT2NpwLdAtVI3bo/w==,iv:pu7d55EB91bGRwZQeNfFzXiNelWRsreSZc+TeMevbuU=,tag:2Kg6g3prOeZ8y386pAJKXQ==,type:str]
    namespace: ENC[AES256_GCM,data:MFYuEVU=,iv:ehRBz14HJecr9ddQ4D6fcmY91IZvhHcHNEChyR2hX9A=,tag:MDVpCzeb1v8AbwQo2cc1ag==,type:str]
type: ENC[AES256_GCM,data:n4Qd7wD9,iv:ADHmj5iQzmp/RbPfVZdz694KAim4gZ68SRCOdvT76Ys=,tag:mEUpHmpniouqJY05Sxj1eg==,type:str]
stringData:
    openai-api-key: ENC[AES256_GCM,data:VbqipoSAUf9xooYE1ljuHyc8kDwAEctdTq9T2hSo3GYRc3pnD3wyGjQAT5yLsmBudfazOLAJLQjmLUIe354pbQXvhuXSKZlUinlPLRCJj6PIlKlynOxzd9EcR5iargeMh4bo2uoknXUoMZXrSKw+SnFY+82mHe2ff9qePnn1HLyb28oeQ4r2v3EYP5DFRtQhR8M/8FI09nEUB5m3NVhBWxqa48w=,iv:YwI6u0mbgccRCqsIQe0I9rHUIYrYIRvVm9WxiElaST4=,tag:+Mkve6PsstydYJoWt2nZFg==,type:str]
    grafana-otlp-endpoint: ENC[AES256_GCM,data:P1H3UxhOth5vHPULimy54re0pwFPRKwAnkQ9xrlAv21ZuQe1joRA214zSWWq5iv+k8TMq3w82FFw,iv:9uOe4ngziJPkGmzGDW+5M8w8yQ6EW+lvbvU7dppd01w=,tag:w34kcJrqXu0vjbQNK844kQ==,type:str]
    grafana-otlp-auth: ENC[AES256_GCM,data:sxTraUoNHB0Im5PtE/9XmLk6LfJJQlxRJnW28vspTgr7IW6AxQjXu1i3JBR2pVI41QboBfrRIgRsFoo1PTGwNh8TAejzwU8e4AfhiBqYI53lUOwKu4hhOqVqoSX2YRqefSAf6ZX+jGvzX9tJGJe14XKq2K8+0xejVrNd7CauEKY1obOv3q4Q+ZRb/44iNS3PRxkyICpffjAy4NkksfJvPCxysp+YxKRY3ZXg7E+coLNNaX7ezIsuDr3EK2SOifueog8yNeEXiDLMlUM8TszXLl8hUjAjnlrLCQLWKS/2TU/YmxVigm6ICkknP2u9YBY6mJv8nq4f,iv:5NXxNvHfo6vt6JnBo2xlcbQQ221Y/oVL39TfcssIlqk=,tag:6biKgX5dmGAWNJdvog8Feg==,type:str]
sops:
    age:
        - recipient: age1qsj5x5cm98dl8r74xp80guvay8kjp0gz5gypqfdjzd9w59kuk5pquhjgef
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmTkRJcEgzbmNXcWQxbHR6
            azlDZGVzOG9qd0NGZG52N2dlRG5lOTVXUEFvCnNib0RNVHFzZVJKZ1RYTEw2QlJT
            ekF0T3pvaVZVTVFJVktycHRaNnRMSFUKLS0tIFlRRWdWTVJiNTJLanc4MW9ub1VJ
            clNJV085c3JCM2Z2QzhMQU8zREJValUKyENmvd39qJp3AuDBHyoeKaFX1ZbQolV4
            aQIgVllmkQjfxvP8mANwedy/PBBT5XIjkMQxf3amznnhWLme5HabZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T05:07:36Z"
    mac: ENC[AES256_GCM,data:CvsJzkbTDyB3kBfgENwGmO/N4sbf7XnISN870uFvv1lpwnyEu8rhwanerRPjInfL+DpgrBlOpPKoE4mn6gkQiIE9VjnrokNHUTpXD6kAaKrn0hH+f+7uVB2dAr0m6eRH2lk8aLUmwKWx2mngUud7hRPO2eoWx4583JDRPgxdtew=,iv:xfgEfRKgmFq+i9fe2CK8YYe11HsjhHF4xQ9r+KlIR00=,tag:y9ercV2qvgBay1/UZ7hXXA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
