apiVersion: ENC[AES256_GCM,data:5OQ=,iv:1i7bwPtc3oS/kTC0TrrmUdIprvuPt54IvBVKkBpBI24=,tag:ckoKS19El6zxQP3JkKd//w==,type:str]
kind: ENC[AES256_GCM,data:QHvuFb3M,iv:EVzG13oL/yx1bi7td/1AtjdXAz5H6jZB12mMfLRL/+g=,tag:27EQbbobiKMzhN7GRbVIGw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:eTyRkjlvziaeJI+7Xg==,iv:GuoGK0hB1aCg+4vpQp8DaXOp26BknhMfhnIy09lyzWM=,tag:NBEUGGu4jey+yvbi74fwvA==,type:str]
    namespace: ENC[AES256_GCM,data:+/WamoI=,iv:XeBddtXKDfVR/kIAHqfWSX+/lyRD2FGFt7L4ILc1DSQ=,tag:sFVYfzmP93ehv1QanooqBw==,type:str]
type: ENC[AES256_GCM,data:z5Ob1E4d,iv:PsCHq9JKwd5ERCy+s6qctJixhqruK2KK4kFcIZv9pxo=,tag:PFwMwD2yTWgLbo+Ss+y3aA==,type:str]
stringData:
    openai-api-key: ENC[AES256_GCM,data:4FVAMPri1QrFfYC/aG1SiiC4bKya2MjNRUee1+i3qAGWS6qixDvw3+Olc2ws/+0AYvshJPYqS6HOIDmlmy7+GtJB7eE8QLHiTkORERgi62H1y3LgtVqC6gnn4IoD+dDlD8Dr4ViIsChfogDyijKlUMTqNrVNtcLqxQUi8yil371JFx0yclGQk368Ax5XsvCYG/GIJojiVCE2L/scxxtUyKGJ/vQ=,iv:dcEQniEreZ71OVJowQ9XKS8X7PbGZdV1o1aHqXoWTDk=,tag:di5Osb7xZQo3JJ+Kbbu71Q==,type:str]
sops:
    age:
        - recipient: age1qsj5x5cm98dl8r74xp80guvay8kjp0gz5gypqfdjzd9w59kuk5pquhjgef
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlM0dqRDI5QUM3WjdWQ1R4
            bEFpR2pvQlJYQWJTZ1d0ZGZiOTVOdkFKdENZCm41RjdqazdUS3Jxakxray81NjJE
            anFSZ041NG9OZFJoN2oyNnlidEZETzgKLS0tICtWY0lzUmFZSVlOajc2QS8zY3pq
            eERjazZ5Zm4ySUtOU3pLenF2K2VCL2MK5UFCMxn4WXhRNgBfnAIezmQjb0rm2UhM
            a9A4K2TfmA3zP+8i66pPHk7ucLN+LKe7wZrnUG81ue7wzAflMV+3Zw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T06:57:06Z"
    mac: ENC[AES256_GCM,data:0De3gEVFSimFluk8PQ7xFKfHZWzD4XXshQ3R0E8DDyif/+jePJTLFViYbsTVdvzMy7gyyjqb5KDdGVhQXFl3cXZ8OvcaEVLXqFNOBNIE9RmEyREFLVJZ09qKmzwdd8Ri/QNvlpIMdUWIsnVOGIjfH0ZG/C7zRCBIKhvFYi+9y98=,iv:fFk7EbEDpGLFs2iTWyja5ELTTmo6LNuhrmBMGwUDYFE=,tag:KpzxvgwuxXl7ZgQJ/7wJog==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
