apiVersion: ENC[AES256_GCM,data:zWY=,iv:+zJsC30j4IXNVZrxcmvs+SVZ0EGJ30pKt3l3rHMIHdk=,tag:i0I+Y/fs74lVXItbCBBx/Q==,type:str]
kind: ENC[AES256_GCM,data:nluQiFKi,iv:2c4B2Uae99eUnUuH4hhjPnih3E2J0UuEZxRtFx4bjxo=,tag:kJvPstnq47jkbvct8p20Eg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Z8QrGfhvjv5RNrxbIw==,iv:G2pbTC/dlViB0miQ6FABqXJqhdvsFXCBsXlO+Fgh30E=,tag:n2RZup9ZYUEsXmmRT4YXVQ==,type:str]
    namespace: ENC[AES256_GCM,data:tC+thMI=,iv:CK8hQxdwyMjyG/VdqevS0pVt2ace6twDN962G57RiCM=,tag:NwCaCJju57A20n3zDyJxJA==,type:str]
type: ENC[AES256_GCM,data:Itpm4bAc,iv:pEtKxo22wwHTnfM3pDaBc+DT7LK/vcVCQ4zzjnRxVr4=,tag:7VobyGw6rS7rlKOWd2qD/A==,type:str]
stringData:
    openai-api-key: ENC[AES256_GCM,data:lYHg/cy9hCEHsPbuNcS1l7COc6Tadg3/Ci7mACJJELkEOSTmvOodMYdrz2CNeOImR/5j7I70oRzAxsZO95CN0Ds4dbMM8WUivGmE3iH80b+a6y4GBaj055B9iaMfqQY0JNFLfbu98UJ6jwN6iIR6FVFweT/bt+6hGxSSnH98qEoQNT6A95wfAd09JI3yqJjHWmP21odEf8fXIvzaaMJoFyzW/8s=,iv:HwAIqeTw4k1bo0iqzEnV4mooSX+4xDjetDXHKrNWpJ8=,tag:XPDy2/KfvUfQzwunZaNgEw==,type:str]
    grafana-otlp-endpoint: ENC[AES256_GCM,data:9TphTuynuRKmmF/LBoPvu/YlQkt1ehzsKNno0fEDiHXon9SqupUTAvfTNwdTLhcs+mPbtTolvOCV,iv:wqH2xPg2ntu2G7t1kHG/kb3+iVzD+DXudzvNTcQM4Mk=,tag:BVF+W0Q9IB7Q4j04X+wGwA==,type:str]
    grafana-otlp-auth: ENC[AES256_GCM,data:cKq5/wfMmVisZujxwYAto3pWG+IVL0d7Gnf1fQ7h/0Bu3IFLKKKTprovwr+Dv1nmFA/ZW8nEWX6O/mHjECKo7gIs4wpy3rAVaC/Z/PxvFjoscm54bWidy19fvCC1qyf3PPlGrKXp3lb53Vp7TBHXiF34RvEmTScsBMEUXv0B9qmpUUHRQyNPqtBbh7+mVqVzH7oa4Kb0pAT0QVN1r4N8NCSTj/+yw669S0rezqNm/UaBKb0GZbe0qcIbLj8yA0gySn+M6gXBOp2f94+SM0ZVJraCnOnhcp6WaIfpT0pm3wL0yeygEyQL8n/9mmya4VfOX848upEn,iv:LRLhpMuHqRxeBix3/1Sg8yPm1TzFE4tm5w4pfx8ozjc=,tag:ZTv15kIiR5iUDMkXCPu3Ew==,type:str]
sops:
    age:
        - recipient: age1qsj5x5cm98dl8r74xp80guvay8kjp0gz5gypqfdjzd9w59kuk5pquhjgef
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJQjFmWVFHTmhmZUhkb1hZ
            UlNuN3lLUm13d1NMb0pmS0xhdXpGZzhSWnc0CkRvYXZBMlF0NWJ6N0IzOHNqTnRR
            UzJ0NmluZTRTRXZIb1I2a0RpdllKdUUKLS0tIEhPVDlzRnEzczRHbU1OR1FxS2Qr
            MmljbnpjMVpUNEpxVE9EeVNuaWZ5VE0K0pHbODbqTRUDVV+T8vzyvxqh7p1N3IiX
            ZhObatxnGFHDXO1CqshWtFLmDEN9H/tsCdqSpiMj4jHXiXE6XeWivg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T04:45:32Z"
    mac: ENC[AES256_GCM,data:9LLnBpegidKWN09C14cyzGjOma166amXEm0uftqc3OxCxA3MHYONBDSI32IJWZporCOpj/ESFy/RkizFNqS1MDcpE4T3urisohYpcqL4fbeqebyJpyezgatKFNH6mX82j3Ize/eZQjc/r9M7POtZ6f8vEZqKfSsQgIP2kx8UXrw=,iv:vg/dyX6s47Y7Hz0bq42xN2Ii0K6tlTTsws8jQ5ZnkiU=,tag:KzNkNCBom1aKijKepkX5Hg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
