apiVersion: apps/v1
kind: Deployment
metadata:
  name: voicevox
  namespace: majel
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: voicevox
  template:
    metadata:
      labels:
        app: voicevox
    spec:
      containers:
        - name: voicevox
          image: voicevox/voicevox_engine:cpu-latest
          args: ["/opt/voicevox_engine/run", "--host", "0.0.0.0", "--cpu_num_threads", "4"]
          ports:
            - containerPort: 50021
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "2Gi"
              cpu: "4000m"
          readinessProbe:
            httpGet:
              path: /speakers
              port: 50021
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /speakers
              port: 50021
            initialDelaySeconds: 60
            periodSeconds: 30
